[package]
name = "rust-sdl2-wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
sdl2 = { version = "*", features = ["raw-window-handle", "gfx", "ttf", ]}
glow = { version = "*" }
mlua = { version = "*", features = ["luau"] }
