[target.wasm32-unknown-emscripten]
rustflags = [
    "-C",
    "link-arg=-s",
    "-C",
    "link-arg=USE_SDL=2",
    "-C",
    "link-arg=-s",
    "-C",
    "link-arg=USE_SDL_GFX=2",

    "-C",
    "link-arg=-s",
    "-C",
    "link-arg=USE_SDL_TTF=2",
    "-C",
    "link-arg=-s",
    "-C",
    "link-arg=DISABLE_DEPRECATED_FIND_EVENT_TARGET_BEHAVIOR=1",

]
